import React from 'react';
import { 
  X, 
  Download, 
  Printer, 
  Award, 
  CheckCircle2, 
  FileText, 
  Sparkles 
} from 'lucide-react';

export default function ReportModal({ isOpen, onClose, profile, careerDNA, skillGaps }) {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-2xl bg-[#0b0f19] border border-slate-800 rounded-2xl shadow-2xl p-6 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 mb-4 border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-950/80 border border-indigo-500/40 flex items-center justify-center text-indigo-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                Student Career Readiness Report
              </h3>
              <p className="text-xs text-slate-400">
                Generated by SkillMap AI Career Intelligence Engine
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Printable Content */}
        <div id="printable-report" className="space-y-4 text-xs text-slate-300">
          {/* Student Banner */}
          <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800 flex items-center justify-between">
            <div>
              <h4 className="text-base font-black text-white">{profile?.name || "Rajat Verma"}</h4>
              <p className="text-xs text-indigo-400 font-semibold">{profile?.headline || "Full Stack & AI Engineer Aspirant"}</p>
              <p className="text-[11px] text-slate-500">{profile?.email || "rajat@skillmap.ai"}</p>
            </div>
            <div className="text-right">
              <span className="text-[10px] text-slate-400 block uppercase">Overall Readiness</span>
              <span className="text-3xl font-black text-emerald-400">{profile?.career_readiness_score || 82}/100</span>
            </div>
          </div>

          {/* 6-Axis Competencies */}
          <div className="p-4 rounded-xl bg-slate-900/50 border border-slate-800">
            <h5 className="font-bold text-white uppercase text-[11px] mb-2.5">AI Career DNA Competencies</h5>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {Object.entries(profile?.competencies || {}).map(([key, val]) => (
                <div key={key} className="p-2 rounded-lg bg-slate-900 border border-slate-800/80 flex justify-between">
                  <span className="capitalize text-slate-400">{key.replace('_', ' ')}</span>
                  <span className="font-bold text-slate-200">{val}%</span>
                </div>
              ))}
            </div>
          </div>

          {/* Top Career Matches */}
          <div className="p-4 rounded-xl bg-slate-900/50 border border-slate-800">
            <h5 className="font-bold text-white uppercase text-[11px] mb-2.5">Target Career Matches</h5>
            <div className="space-y-1.5">
              {(careerDNA?.top_matches || [
                { title: "Software Engineer", match_score: 88 },
                { title: "Data Engineer", match_score: 81 },
                { title: "AI/ML Engineer", match_score: 74 },
                { title: "Cybersecurity Analyst", match_score: 61 }
              ]).map((c, i) => (
                <div key={i} className="flex items-center justify-between py-1 border-b border-slate-800/60 last:border-0">
                  <span className="text-slate-300 font-semibold">{c.title}</span>
                  <span className="font-bold text-emerald-400">{c.match_score}% Match</span>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Next Actions */}
          <div className="p-4 rounded-xl bg-indigo-950/30 border border-indigo-500/30 text-[11px] space-y-1">
            <span className="font-bold text-indigo-300 block mb-1">Recommended Next Steps:</span>
            <p>1. Complete System Design basics (URL shortener capstone) to bridge the 40% gap.</p>
            <p>2. Complete Docker containerization module for the E-Commerce API.</p>
            <p>3. Re-run Mock Interview Simulator to improve technical communication score.</p>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-5 pt-3 border-t border-slate-800 flex items-center justify-end gap-3">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-white transition-colors"
          >
            <Printer className="w-4 h-4" />
            <span>Print / Save PDF</span>
          </button>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-500 transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
